/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @file        Test-CFPP-Date.cpp
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @abstract    Unit tests for CF::Date
 */

#include <CF++.hpp>
#include <GoogleMock/GoogleMock.h>

using namespace testing;

TEST( CFPP_Date, CurrentDate )
{
    CFAbsoluteTime t;
    CF::Date       d;
    
    t = CFAbsoluteTimeGetCurrent();
    d = CF::Date::CurrentDate();
    
    ASSERT_TRUE( d.IsValid() );
    
    ASSERT_GT(   d.GetValue(), 0 );
    ASSERT_TRUE( d.GetValue() > t - 1 );
    ASSERT_TRUE( d.GetValue() < t + 1 );
}

TEST( CFPP_Date, CTOR )
{
    CFAbsoluteTime t;
    CF::Date       d;
    
    t = CFAbsoluteTimeGetCurrent();
    
    ASSERT_TRUE( d.IsValid() );
    
    ASSERT_GT(   d.GetValue(), 0 );
    ASSERT_TRUE( d.GetValue() > t - 1 );
    ASSERT_TRUE( d.GetValue() < t + 1 );
}

TEST( CFPP_Date, CTOR_CFType )
{
    CFAbsoluteTime t;
    CF::Date       d1( static_cast< CFTypeRef >( CF::Date::CurrentDate().GetCFObject() ) );
    CF::Date       d2( static_cast< CFTypeRef >( NULL ) );
    
    t = CFAbsoluteTimeGetCurrent();
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    
    ASSERT_GT(   d1.GetValue(), 0 );
    ASSERT_TRUE( d1.GetValue() > t - 1 );
    ASSERT_TRUE( d1.GetValue() < t + 1 );
}

TEST( CFPP_Date, CTOR_CFDate )
{
    CFAbsoluteTime t;
    CF::Date       d1( static_cast< CFDateRef >( CF::Date::CurrentDate().GetCFObject() ) );
    CF::Date       d2( static_cast< CFDateRef >( NULL ) );
    
    t = CFAbsoluteTimeGetCurrent();
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    
    ASSERT_GT(   d1.GetValue(), 0 );
    ASSERT_TRUE( d1.GetValue() > t - 1 );
    ASSERT_TRUE( d1.GetValue() < t + 1 );
}

TEST( CFPP_Date, CTOR_CFAbsoluteTime )
{
    CFAbsoluteTime t;
    CF::Date       d1( CFAbsoluteTimeGetCurrent() );
    CF::Date       d2( static_cast< CFAbsoluteTime >(  0 ) );
    CF::Date       d3( static_cast< CFAbsoluteTime >( -1 ) );
    
    t = CFAbsoluteTimeGetCurrent();
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    ASSERT_TRUE( d3.IsValid() );
    
    ASSERT_GT(   d1.GetValue(), 0 );
    ASSERT_TRUE( d1.GetValue() > t - 1 );
    ASSERT_TRUE( d1.GetValue() < t + 1 );
}

TEST( CFPP_Date, CCTOR )
{
    CF::Date d1;
    CF::Date d2( d1 );
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    
    ASSERT_GT(   d2.GetValue(), 0 );
    ASSERT_TRUE( d2.GetValue() > d1.GetValue() - 1 );
    ASSERT_TRUE( d2.GetValue() < d1.GetValue() + 1 );
}

#ifdef CFPP_HAS_CPP11
TEST( CFPP_Date, MCTOR )
{
    CF::Date d1;
    CF::Date d2( std::move( d1 ) );
    
    ASSERT_FALSE( d1.IsValid() );
    ASSERT_TRUE(  d2.IsValid() );
}
#endif

TEST( CFPP_Date, OperatorAssignDate )
{
    CF::Date d1;
    CF::Date d2( static_cast< CFDateRef >( NULL ) );
    CF::Date d3( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    ASSERT_FALSE( d3.IsValid() );
    
    d2 = d1;
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    
    ASSERT_GT(   d2.GetValue(), 0 );
    ASSERT_TRUE( d2.GetValue() > d1.GetValue() - 1 );
    ASSERT_TRUE( d2.GetValue() < d1.GetValue() + 1 );
    
    d2 = d3;
    
    ASSERT_FALSE( d2.IsValid() );
}

TEST( CFPP_Date, OperatorAssignCFType )
{
    CF::Date d1;
    CF::Date d2( static_cast< CFDateRef >( NULL ) );
    CF::Date d3( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    ASSERT_FALSE( d3.IsValid() );
    
    d2 = static_cast< CFTypeRef >( d1.GetCFObject() );
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    
    ASSERT_GT(   d2.GetValue(), 0 );
    ASSERT_TRUE( d2.GetValue() > d1.GetValue() - 1 );
    ASSERT_TRUE( d2.GetValue() < d1.GetValue() + 1 );
    
    d2 = static_cast< CFTypeRef >( d3.GetCFObject() );
    
    ASSERT_FALSE( d2.IsValid() );
}

TEST( CFPP_Date, OperatorAssignCFDate )
{
    CF::Date d1;
    CF::Date d2( static_cast< CFDateRef >( NULL ) );
    CF::Date d3( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    ASSERT_FALSE( d3.IsValid() );
    
    d2 = static_cast< CFDateRef >( d1.GetCFObject() );
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    
    ASSERT_GT(   d2.GetValue(), 0 );
    ASSERT_TRUE( d2.GetValue() > d1.GetValue() - 1 );
    ASSERT_TRUE( d2.GetValue() < d1.GetValue() + 1 );
    
    d2 = static_cast< CFDateRef >( d3.GetCFObject() );
    
    ASSERT_FALSE( d2.IsValid() );
}

TEST( CFPP_Date, OperatorAssignCFAbsoluteTime )
{
    CF::Date d1;
    CF::Date d2( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1.IsValid() );
    ASSERT_FALSE( d2.IsValid() );
    
    d2 = d1.GetValue();
    
    ASSERT_TRUE( d1.IsValid() );
    ASSERT_TRUE( d2.IsValid() );
    
    ASSERT_GT(   d2.GetValue(), 0 );
    ASSERT_TRUE( d2.GetValue() > d1.GetValue() - 1 );
    ASSERT_TRUE( d2.GetValue() < d1.GetValue() + 1 );
    
    d2 = static_cast< CFAbsoluteTime >( 0 );
    
    ASSERT_TRUE( d2.IsValid() );
    ASSERT_TRUE( d2.GetValue() > -1 );
    ASSERT_TRUE( d2.GetValue() <  1 );
    
    d2 = static_cast< CFAbsoluteTime >( -1 );
    
    ASSERT_TRUE( d2.IsValid() );
    ASSERT_TRUE( d2.GetValue() > -2 );
    ASSERT_TRUE( d2.GetValue() <  0 );
}

TEST( CFPP_Date, OperatorEqualDate )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1 == d2 );
    ASSERT_FALSE( d1 == d3 );
    ASSERT_FALSE( d1 == d4 );
    
    ASSERT_FALSE( d3 == d1 );
    ASSERT_TRUE(  d3 == d3 );
    ASSERT_FALSE( d3 == d4 );
    
    ASSERT_FALSE( d4 == d1 );
    ASSERT_FALSE( d4 == d3 );
    ASSERT_FALSE( d4 == d4 );
}

TEST( CFPP_Date, OperatorEqualCFType )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1 == static_cast< CFTypeRef >( d2.GetCFObject() ) );
    ASSERT_FALSE( d1 == static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d1 == static_cast< CFTypeRef >( d4.GetCFObject() ) );
    
    ASSERT_FALSE( d3 == static_cast< CFTypeRef >( d1.GetCFObject() ) );
    ASSERT_TRUE(  d3 == static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d3 == static_cast< CFTypeRef >( d4.GetCFObject() ) );
    
    ASSERT_FALSE( d4 == static_cast< CFTypeRef >( d1.GetCFObject() ) );
    ASSERT_FALSE( d4 == static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d4 == static_cast< CFTypeRef >( d4.GetCFObject() ) );
}

TEST( CFPP_Date, OperatorEqualCFDate )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1 == static_cast< CFDateRef >( d2.GetCFObject() ) );
    ASSERT_FALSE( d1 == static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d1 == static_cast< CFDateRef >( d4.GetCFObject() ) );
    
    ASSERT_FALSE( d3 == static_cast< CFDateRef >( d1.GetCFObject() ) );
    ASSERT_TRUE(  d3 == static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d3 == static_cast< CFDateRef >( d4.GetCFObject() ) );
    
    ASSERT_FALSE( d4 == static_cast< CFDateRef >( d1.GetCFObject() ) );
    ASSERT_FALSE( d4 == static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_FALSE( d4 == static_cast< CFDateRef >( d4.GetCFObject() ) );
}

TEST( CFPP_Date, OperatorEqualCFAbsoluteTime )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_TRUE(  d1 == d2.GetValue() );
    ASSERT_FALSE( d1 == d3.GetValue() );
    ASSERT_FALSE( d1 == d4.GetValue() );
    
    ASSERT_FALSE( d3 == d1.GetValue() );
    ASSERT_TRUE(  d3 == d3.GetValue() );
    ASSERT_TRUE(  d3 == d4.GetValue() );
    
    ASSERT_FALSE( d4 == d1.GetValue() );
    ASSERT_FALSE( d4 == d3.GetValue() );
    ASSERT_FALSE( d4 == d4.GetValue() );
}

TEST( CFPP_Date, OperatorNotEqualDate )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_FALSE( d1 != d2 );
    ASSERT_TRUE(  d1 != d3 );
    ASSERT_TRUE(  d1 != d4 );
    
    ASSERT_TRUE(  d3 != d1 );
    ASSERT_FALSE( d3 != d3 );
    ASSERT_TRUE(  d3 != d4 );
    
    ASSERT_TRUE( d4 != d1 );
    ASSERT_TRUE( d4 != d3 );
    ASSERT_TRUE( d4 != d4 );
}

TEST( CFPP_Date, OperatorNotEqualCFType )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_FALSE( d1 != static_cast< CFTypeRef >( d2.GetCFObject() ) );
    ASSERT_TRUE(  d1 != static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_TRUE(  d1 != static_cast< CFTypeRef >( d4.GetCFObject() ) );
    
    ASSERT_TRUE(  d3 != static_cast< CFTypeRef >( d1.GetCFObject() ) );
    ASSERT_FALSE( d3 != static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_TRUE(  d3 != static_cast< CFTypeRef >( d4.GetCFObject() ) );
    
    ASSERT_TRUE( d4 != static_cast< CFTypeRef >( d1.GetCFObject() ) );
    ASSERT_TRUE( d4 != static_cast< CFTypeRef >( d3.GetCFObject() ) );
    ASSERT_TRUE( d4 != static_cast< CFTypeRef >( d4.GetCFObject() ) );
}

TEST( CFPP_Date, OperatorNotEqualCFDate )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_FALSE( d1 != static_cast< CFDateRef >( d2.GetCFObject() ) );
    ASSERT_TRUE(  d1 != static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_TRUE(  d1 != static_cast< CFDateRef >( d4.GetCFObject() ) );
    
    ASSERT_TRUE(  d3 != static_cast< CFDateRef >( d1.GetCFObject() ) );
    ASSERT_FALSE( d3 != static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_TRUE(  d3 != static_cast< CFDateRef >( d4.GetCFObject() ) );
    
    ASSERT_TRUE( d4 != static_cast< CFDateRef >( d1.GetCFObject() ) );
    ASSERT_TRUE( d4 != static_cast< CFDateRef >( d3.GetCFObject() ) );
    ASSERT_TRUE( d4 != static_cast< CFDateRef >( d4.GetCFObject() ) );
}

TEST( CFPP_Date, OperatorNotEqualCFAbsoluteTime )
{
    CF::Date d1;
    CF::Date d2( d1 );
    CF::Date d3( static_cast< CFAbsoluteTime >( 0 ) );
    CF::Date d4( static_cast< CFDateRef >( NULL ) );
    
    ASSERT_FALSE( d1 != d2.GetValue() );
    ASSERT_TRUE(  d1 != d3.GetValue() );
    ASSERT_TRUE(  d1 != d4.GetValue() );
    
    ASSERT_TRUE(  d3 != d1.GetValue() );
    ASSERT_FALSE( d3 != d3.GetValue() );
    ASSERT_FALSE( d3 != d4.GetValue() );
    
    ASSERT_TRUE( d4 != d1.GetValue() );
    ASSERT_TRUE( d4 != d3.GetValue() );
    ASSERT_TRUE( d4 != d4.GetValue() );
}

TEST( CFPP_Date, OperatorGreaterOrEqualDate )
{}

TEST( CFPP_Date, OperatorGreaterOrEqualCFDate )
{}

TEST( CFPP_Date, OperatorGreaterOrEqualCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorLesserOrEqualDate )
{}

TEST( CFPP_Date, OperatorLesserOrEqualCFDate )
{}

TEST( CFPP_Date, OperatorLesserOrEqualCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorGreaterDate )
{}

TEST( CFPP_Date, OperatorGreaterCFDate )
{}

TEST( CFPP_Date, OperatorGreaterCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorLesserDate )
{}

TEST( CFPP_Date, OperatorLesserCFDate )
{}

TEST( CFPP_Date, OperatorLesserCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorPlusEqualDate )
{}

TEST( CFPP_Date, OperatorPlusEqualCFDate )
{}

TEST( CFPP_Date, OperatorPlusEqualCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorMinusEqualDate )
{}

TEST( CFPP_Date, OperatorMinusEqualCFDate )
{}

TEST( CFPP_Date, OperatorMinusEqualCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorPlusDate )
{}

TEST( CFPP_Date, OperatorPlusCFDate )
{}

TEST( CFPP_Date, OperatorPlusCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorMinusDate )
{}

TEST( CFPP_Date, OperatorMinusCFDate )
{}

TEST( CFPP_Date, OperatorMinusCFAbsoluteTime )
{}

TEST( CFPP_Date, OperatorPrefixIncrement )
{}

TEST( CFPP_Date, OperatorPostfixIncrement )
{}

TEST( CFPP_Date, OperatorPrefixDecrement )
{}

TEST( CFPP_Date, OperatorPostfixDecrement )
{}

TEST( CFPP_Date, CastToCFAbsoluteTime )
{}

TEST( CFPP_Date, GetTypeID )
{}

TEST( CFPP_Date, GetCFObject )
{}

TEST( CFPP_Date, GetValue )
{}

TEST( CFPP_Date, SetValue )
{}

TEST( CFPP_Date, Swap )
{}
