/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @file        CFPP-Data.cpp
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @abstract    CoreFoundation++ CFDataRef wrapper
 */

#include <CF++.hpp>

namespace CF
{
    Data::Data( void )
    {
        this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
    }
    
    Data::Data( const Data & value )
    {
        if( value._cfObject != NULL )
        {
            this->_cfObject = CFDataCreateMutableCopy( static_cast< CFAllocatorRef >( NULL ), 0, value._cfObject );
        }
        else
        {
            this->_cfObject = NULL;
        }
    }
    
    Data::Data( CFTypeRef value )
    {
        if( value != NULL && CFGetTypeID( value ) == this->GetTypeID() )
        {
            this->_cfObject = CFDataCreateMutableCopy( static_cast< CFAllocatorRef >( NULL ), 0, static_cast< CFDataRef >( value ) );
        }
        else
        {
            this->_cfObject = NULL;
        }
    }
    
    Data::Data( CFDataRef value )
    {
        if( value != NULL && CFGetTypeID( value ) == this->GetTypeID() )
        {
            this->_cfObject = CFDataCreateMutableCopy( static_cast< CFAllocatorRef >( NULL ), 0, static_cast< CFDataRef >( value ) );
        }
        else
        {
            this->_cfObject = NULL;
        }
    }
    
    Data::Data( CFStringRef value )
    {
        if( value != NULL && CFGetTypeID( value ) == CFStringGetTypeID() )
        {
            this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
            
            CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( CFStringGetCStringPtr( value, kCFStringEncodingUTF8 ) ), CFStringGetLength( value ) );
        }
        else
        {
            this->_cfObject = NULL;
        }
    }
    
    Data::Data( std::string value )
    {
        this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
        
        CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( value.c_str() ), static_cast< CFIndex >( value.length() ) );
    }
    
    Data::Data( Byte * value, CFIndex length )
    {
        this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
        
        CFDataAppendBytes( this->_cfObject, value, length );
    }
    
    #ifdef CFPP_HAS_CPP11
    Data::Data( Data && value )
    {
        this->_cfObject = value._cfObject;
        value._cfObject = NULL;
    }
    #endif
    
    Data::~Data( void )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
            
            this->_cfObject = NULL;
        }
    }
          
    Data & Data::operator = ( Data value )
    {
        swap( *( this ), value );
        
        return *( this );
    }
    
    Data & Data::operator = ( CFTypeRef value )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
        }
        
        if( value != NULL && CFGetTypeID( value ) == this->GetTypeID() )
        {
            this->_cfObject = CFDataCreateMutableCopy( static_cast< CFAllocatorRef >( NULL ), 0, static_cast< CFDataRef >( value ) );
        }
        else
        {
            this->_cfObject = NULL;
        }
        
        return *( this );
    }
    
    Data & Data::operator = ( CFDataRef value )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
        }
        
        if( value != NULL && CFGetTypeID( value ) == this->GetTypeID() )
        {
            this->_cfObject = CFDataCreateMutableCopy( static_cast< CFAllocatorRef >( NULL ), 0, value );
        }
        else
        {
            this->_cfObject = NULL;
        }
        
        return *( this );
    }
    
    Data & Data::operator = ( CFStringRef value )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
        }
        
        if( value != NULL && CFGetTypeID( value ) == CFStringGetTypeID() )
        {
            this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
            
            CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( CFStringGetCStringPtr( value, kCFStringEncodingUTF8 ) ), CFStringGetLength( value ) );
        }
        else
        {
            this->_cfObject = NULL;
        }
        
        return *( this );
    }
    
    Data & Data::operator = ( std::string value )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
        }
        
        this->_cfObject = CFDataCreateMutable( static_cast< CFAllocatorRef >( NULL ), 0 );
        
        CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( value.c_str() ), static_cast< CFIndex >( value.length() ) );
        
        return *( this );
    }
    
    Data::operator const Byte * () const
    {
        if( this->_cfObject == NULL )
        {
            return NULL;
        }
        
        return CFDataGetBytePtr( this->_cfObject );
    }
    
    Data::operator std::string () const
    {
        std::string s;
        
        if( this->_cfObject == NULL )
        {
            return s;
        }
        
        s = std::string( reinterpret_cast< const char * >( CFDataGetBytePtr( this->_cfObject ) ) );
        
        return s;
    }
    
    Byte Data::operator [] ( int index ) const
    {
        const Byte * bytes;
        
        if( index >= this->GetLength() )
        {
            return 0;
        }
        
        bytes = this->GetBytePtr();
        
        return bytes[ index ];
    }
            
    Data & Data::operator += ( Byte value )
    {
        if( this->_cfObject != NULL )
        {
            CFDataAppendBytes( this->_cfObject, &value, 1 );
        }
        
        return *( this );
    }
    
    Data & Data::operator += ( CFStringRef value )
    {
        if( this->_cfObject != NULL && value != NULL && CFGetTypeID( value ) == CFStringGetTypeID() )
        {
            CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( CFStringGetCStringPtr( value, kCFStringEncodingUTF8 ) ), CFStringGetLength( value ) );
        }
        
        return *( this );
    }
    
    Data & Data::operator += ( CFDataRef value )
    {
        if( this->_cfObject != NULL && value != NULL && CFGetTypeID( value ) == this->GetTypeID() )
        {
            CFDataAppendBytes( this->_cfObject, CFDataGetBytePtr( value ), CFDataGetLength( value ) );
        }
        
        return *( this );
    }
    
    Data & Data::operator += ( std::string value )
    {
        if( this->_cfObject != NULL )
        {
            CFDataAppendBytes( this->_cfObject, reinterpret_cast< const UInt8 * >( value.c_str() ), static_cast< CFIndex >( value.length() ) );
        }
        
        return *( this );
    }
    
    CFTypeID Data::GetTypeID( void ) const
    {
        return CFDataGetTypeID();
    }
    
    CFTypeRef Data::GetCFObject( void ) const
    {
        return this->_cfObject;
    }
    
    CFIndex Data::GetLength( void ) const
    {
        if( this->_cfObject == NULL )
        {
            return 0;
        }
        
        return CFDataGetLength( this->_cfObject );
    }
    
    void Data::SetLength( CFIndex length ) const
    {
        if( this->_cfObject == NULL )
        {
            return;
        }
        
        CFDataSetLength( this->_cfObject, length );
    }
    
    void Data::IncreaseLength( CFIndex extraLength ) const
    {
        if( this->_cfObject == NULL )
        {
            return;
        }
        
        CFDataIncreaseLength( this->_cfObject, extraLength );
    }
    
    const Byte * Data::GetBytePtr( void ) const
    {
        if( this->_cfObject == NULL )
        {
            return NULL;
        }
        
        return CFDataGetBytePtr( this->_cfObject );
    }
    
    Byte * Data::GetMutableBytePtr( void ) const
    {
        if( this->_cfObject == NULL )
        {
            return NULL;
        }
        
        return CFDataGetMutableBytePtr( this->_cfObject );
    }
    
    void Data::GetBytes( CFRange range, Byte * bytes ) const
    {
        if( this->_cfObject == NULL || bytes == NULL )
        {
            return;
        }
        
        CFDataGetBytes( this->_cfObject, range, bytes );
    }
    
    void Data::AppendBytes( Byte * bytes, CFIndex length ) const
    {
        if( this->_cfObject == NULL || bytes == NULL )
        {
            return;
        }
        
        CFDataAppendBytes( this->_cfObject, bytes, length );
    }
    
    void Data::ReplaceBytes( CFRange range, Byte * newBytes, CFIndex newLength ) const
    {
        if( this->_cfObject == NULL || newBytes == NULL )
        {
            return;
        }
        
        CFDataReplaceBytes( this->_cfObject, range, newBytes, newLength );
    }
    
    void Data::DeleteBytes( CFRange range ) const
    {
        if( this->_cfObject == NULL )
        {
            return;
        }
        
        CFDataDeleteBytes( this->_cfObject, range );
    }
    
    Data::Iterator Data::begin( void )
    {
        return Iterator( this->_cfObject, this->GetLength() );
    }
    
    Data::Iterator Data::end( void )
    {
        return Iterator( this->_cfObject, this->GetLength(), this->GetLength() );
    }
    
    void swap( Data & v1, Data & v2 )
    {
        using std::swap;
        
        swap( v1._cfObject, v2._cfObject );
    }
    
    Data::Iterator::Iterator( void ):
        _cfObject( NULL ),
        _length( 0 ),
        _pos( 0 ),
        _bp( NULL )
    {}
    
    Data::Iterator::Iterator( const Iterator & value ):
        _cfObject( value._cfObject ),
        _length( value._length ),
        _pos( value._pos ),
        _bp( value._bp )
    {
        if( this->_cfObject != NULL )
        {
            CFRetain( this->_cfObject );
        }
    }
    
    Data::Iterator::Iterator( CFDataRef data, CFIndex length, CFIndex pos ):
        _cfObject( data ),
        _length( length ),
        _pos( pos ),
        _bp( NULL )
    {
        if( this->_cfObject != NULL )
        {
            CFRetain( this->_cfObject );
            
            this->_bp = CFDataGetBytePtr( this->_cfObject );
        }
    }
    
    #ifdef CFPP_HAS_CPP11
    Data::Iterator::Iterator( Iterator && value )
    {
        this->_cfObject = value._cfObject;
        value._cfObject = NULL;
        this->_length   = value._length;
        value._length   = 0;
        this->_pos      = value._pos;
        value._pos      = 0;
        this->_bp       = value._bp;
        value._bp       = NULL;
    }
    #endif
    
    Data::Iterator::~Iterator( void )
    {
        if( this->_cfObject != NULL )
        {
            CFRelease( this->_cfObject );
        }
    }
    
    Data::Iterator & Data::Iterator::operator = ( Iterator value )
    {
        swap( *( this ), value );
        
        return *( this );
    }
    
    Data::Iterator & Data::Iterator::operator ++( void )
    {
        this->_pos++;
        
        return *( this );
    }
    
    Data::Iterator Data::Iterator::operator ++( int )
    {
        Iterator it( *( this ) );
        
        operator++();
        
        return it;
    }
    
    Data::Iterator & Data::Iterator::operator --( void )
    {
        this->_pos--;
        
        return *( this );
    }
    
    Data::Iterator Data::Iterator::operator --( int )
    {
        Iterator it( *( this ) );
        
        operator--();
        
        return it;
    }
    
    Data::Iterator & Data::Iterator::operator += ( CFIndex value )
    {
        this->_pos += value;
        
        return *( this );
    }
    
    Data::Iterator & Data::Iterator::operator -= ( CFIndex value )
    {
        this->_pos -= value;
        
        return *( this );
    }
    
    Data::Iterator Data::Iterator::operator + ( CFIndex value )
    {
        Iterator i;
        
        i = *( this );
        
        return i += value;
    }
    
    Data::Iterator Data::Iterator::operator - ( CFIndex value )
    {
        Iterator i;
        
        i = *( this );
        
        return i -= value;
    }
    
    bool Data::Iterator::operator == ( const Iterator & value ) const
    {
        if( this->_cfObject != value._cfObject )
        {
            return false;
        }
        
        if( this->_length != value._length )
        {
            return false;
        }
        
        if( this->_pos != value._pos )
        {
            return false;
        }
        
        return true;
    }
    
    bool Data::Iterator::operator != ( const Iterator & value ) const
    {
        return !( *( this ) == value );
    }
    
    Data::Byte Data::Iterator::operator * ( void ) const
    {
        if( this->_cfObject == NULL )
        {
            return 0;
        }
        
        if( this->_bp == NULL )
        {
            return 0;
        }
        
        if( this->_pos < 0 )
        {
            return 0;
        }
        
        if( this->_pos >= this->_length )
        {
            return 0;
        }
        
        return this->_bp[ this->_pos ];
    }
    
    Data::Iterator::operator Data::Byte () const
    {
        return operator*();
    }
    
    void swap( Data::Iterator::Iterator & v1, Data::Iterator::Iterator & v2 )
    {
        using std::swap;
        
        swap( v1._cfObject, v2._cfObject );
        swap( v1._length,   v2._length );
        swap( v1._pos,      v2._pos );
        swap( v1._bp,       v2._bp );
    }
}
